#!/usr/bin/env bash
# configures nginx to run and listen to port 80

# creates a symbolic link (-s option) between the Nginx configuration file
# and the enabled sites directory
ln -af /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx restart
# terminates the first nginx process ID
kill "$(pgrep 'nginx' | head -1)"
